Build:
	mkdir Build
	mkdir Build/Public
	cp -R Orchid/Public/ Build/Public/
	cp Orchid/Sample.py Build/
	python3 Setup.py
Install:
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	brew install python3