import py_compile
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig1.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig1_0.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig1_1.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig1_1.pyc", optimize=2)

py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig2.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig2_0.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig2_1.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig2_1.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig2_2.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig2_2.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig2_3.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig2_3.pyc", optimize=2)

py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_0.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_1.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_1.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_2.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_2.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_3.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_3.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_4.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_5.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_5.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_6.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_6.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_7.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig3_7.pyc", optimize=2)

py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_1.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_2.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_3.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_4.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_5.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_6.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_7.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_8.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_9.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_10.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_11.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_12.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_13.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_14.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4_15.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig4.pyc", optimize=2)

py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig5.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig5.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig6.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Code/Dig6.pyc", optimize=2)
py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Interperet/Test.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/Computer1/Interperet/Test.pyc", optimize=2)
#py_compile.compile('C:/Users/Administrator/Desktop/Code/Orchestrator/REF/Lib1.py',"C:/Users/Administrator/Desktop/Code/Orchestrator/REF/Lib1.pyc", optimize=2)